# Generated by Django 5.2 on 2025-06-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(blank=True, max_length=100, null=True)),
                ('component_name', models.CharField(max_length=50)),
                ('result_value', models.CharField(max_length=50)),
                ('result_unit', models.CharField(max_length=20)),
                ('verified_by', models.IntegerField()),
                ('verified_date', models.DateTimeField()),
                ('result_status', models.CharField(default='recorded', max_length=20)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
            ],
        ),
    ]
