# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(default='기타', max_length=50)),
                ('alias_name', models.CharField(max_length=100, unique=True)),
                ('test_type_keywords', models.TextField(help_text='Comma-separated keywords')),
            ],
        ),
        migrations.CreateModel(
            name='LOINCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('component', models.TextField(blank=True, null=True)),
                ('property', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True)),
                ('test_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=50)),
                ('loinc_code', models.CharField(max_length=50)),
                ('collection_date', models.DateTimeField()),
                ('test_type', models.CharField(default='기타', max_length=50)),
                ('sample_status', models.CharField(default='collected', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.testorder')),
            ],
        ),
    ]
