# Generated by Django 4.2 on 2025-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
