# Generated by Django 4.2 on 2025-06-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='patient_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
