# Generated by Django 5.2 on 2025-06-04 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('body_part', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=10)),
                ('requesting_physician', models.CharField(max_length=100)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('scheduled_exam_datetime', models.DateTimeField(blank=True, null=True)),
                ('interpreting_physician', models.CharField(blank=True, max_length=100, null=True)),
                ('study_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=50, null=True)),
                ('study_status', models.CharField(default='requested', max_length=20)),
                ('report_status', models.CharField(default='pending', max_length=20)),
                ('workflow_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workflow_status', models.CharField(choices=[('emr_requested', 'EMR 요청'), ('ris_received', 'RIS 접수'), ('scheduled', '검사 예약'), ('in_progress', '검사 진행중'), ('image_uploaded', '영상 업로드'), ('ai_analyzing', 'AI 분석중'), ('ai_completed', 'AI 분석완료'), ('reading_pending', '판독 대기'), ('reading_in_progress', '판독 진행중'), ('reading_completed', '판독 완료'), ('report_approved', '리포트 승인'), ('emr_delivered', 'EMR 전송완료'), ('workflow_completed', '워크플로우 완료'), ('cancelled', '취소'), ('error', '오류')], default='emr_requested', max_length=30)),
                ('emr_requested_at', models.DateTimeField(blank=True, null=True)),
                ('ris_received_at', models.DateTimeField(blank=True, null=True)),
                ('image_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reading_started_at', models.DateTimeField(blank=True, null=True)),
                ('reading_completed_at', models.DateTimeField(blank=True, null=True)),
                ('emr_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('study_description', models.TextField(blank=True, null=True)),
                ('clinical_info', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('ai_analysis_result', models.JSONField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('report_text', models.TextField(blank=True, null=True)),
                ('report_created_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('workflow_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worklist_studyrequest',
                'indexes': [models.Index(fields=['workflow_status', 'request_datetime'], name='workflow_status_time_idx'), models.Index(fields=['patient_id', 'workflow_status'], name='patient_workflow_idx'), models.Index(fields=['modality', 'workflow_status'], name='modality_workflow_idx'), models.Index(fields=['requesting_physician'], name='requesting_physician_idx'), models.Index(fields=['workflow_id'], name='workflow_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='worklist.studyrequest')),
            ],
            options={
                'db_table': 'workflow_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DICOMMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthanc_study_id', models.CharField(max_length=255)),
                ('orthanc_series_id', models.CharField(max_length=255)),
                ('orthanc_instance_id', models.CharField(max_length=255)),
                ('study_instance_uid', models.CharField(max_length=255)),
                ('series_instance_uid', models.CharField(max_length=255)),
                ('sop_instance_uid', models.CharField(max_length=255)),
                ('series_description', models.CharField(blank=True, max_length=255, null=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('image_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_mappings', to='worklist.studyrequest')),
            ],
            options={
                'db_table': 'dicom_mapping',
                'unique_together': {('study_request', 'orthanc_instance_id')},
            },
        ),
    ]
