# Generated by Django 4.2 on 2025-06-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('body_part', models.CharField(max_length=50)),
                ('modality', models.CharField(choices=[('CR', 'CR (X-ray)'), ('CT', 'CT (Computed Tomography)'), ('MR', 'MR (MRI)'), ('US', 'US (Ultrasound)'), ('NM', 'NM (Nuclear Medicine)'), ('PT', 'PT (PET Scan)'), ('DX', 'DX (Digital Radiography)'), ('XA', 'XA (Angiography)'), ('MG', 'MG (Mammography)')], max_length=20)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('requesting_physician', models.CharField(max_length=100)),
                ('scheduled_exam_datetime', models.DateTimeField(blank=True, null=True)),
                ('interpreting_physician', models.CharField(blank=True, max_length=100, null=True)),
                ('study_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=100, null=True)),
                ('study_status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('report_status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
