# Generated by Django 5.2.1 on 2025-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
