# Generated by Django 4.2 on 2025-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='study_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
