# Generated by Django 4.2 on 2025-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0002_extend_studyrequest_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrequest',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='dicommapping',
            name='unique_study_instance_mapping',
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='accession_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='body_part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='modality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='patient_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='report_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='study_status',
            field=models.CharField(default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='study_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dicommapping',
            unique_together={('study_request', 'orthanc_instance_id')},
        ),
        migrations.AlterModelTable(
            name='studyrequest',
            table='worklist_studyrequest',
        ),
    ]
