# Generated by Django 5.2.1 on 2025-05-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0002_alter_studyrequest_request_datetime'),
    ]

    operations = [
    ]
