# Generated by Django 5.2.1 on 2025-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0003_update_complete_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrequest',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='studyrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='interpreting_physician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='report_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='scheduled_exam_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='study_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='sex',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1),
        ),
    ]
