# Generated by Django 5.2.1 on 2025-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0004_alter_studyrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
    ]
