# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('encounter_id', models.AutoField(primary_key=True, serialize=False)),
                ('encounter_type', models.IntegerField()),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('encounter_datetime', models.DateTimeField()),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('visit_id', models.IntegerField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'encounter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('patient_identifier_id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('identifier_type', models.IntegerField()),
                ('preferred', models.BooleanField(default=False)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'patient_identifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_estimated', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.IntegerField(null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('person_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('prefix', models.CharField(max_length=50, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('family_name', models.CharField(max_length=50)),
                ('family_name2', models.CharField(max_length=50, null=True)),
                ('family_name_suffix', models.CharField(max_length=50, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'person_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openmrs_models.person')),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
