# Generated by Django 4.2 on 2025-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.AutoField(primary_key=True, serialize=False)),
                ('retired', models.BooleanField(default=False)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_text', models.TextField(blank=True, null=True)),
                ('datatype_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('is_set', models.BooleanField(default=False)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptName',
            fields=[
                ('concept_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=50)),
                ('locale_preferred', models.BooleanField(default=False)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'concept_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('obs_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('obs_datetime', models.DateTimeField()),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('obs_group_id', models.IntegerField(blank=True, null=True)),
                ('value_group_id', models.IntegerField(blank=True, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=255, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_coded_name_id', models.IntegerField(blank=True, null=True)),
                ('value_drug', models.IntegerField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('value_modifier', models.CharField(blank=True, max_length=2, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_complex', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
                ('previous_version', models.IntegerField(blank=True, null=True)),
                ('form_namespace_and_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'obs',
                'managed': False,
            },
        ),
    ]
