# Generated by Django 4.2 on 2025-06-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_models', '0002_concept_conceptname_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptClass',
            fields=[
                ('concept_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('retired', models.BooleanField(default=False)),
                ('retired_by', models.IntegerField(blank=True, null=True)),
                ('date_retired', models.DateTimeField(blank=True, null=True)),
                ('retire_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'concept_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptDatatype',
            fields=[
                ('concept_datatype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hl7_abbreviation', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('retired', models.BooleanField(default=False)),
                ('retired_by', models.IntegerField(blank=True, null=True)),
                ('date_retired', models.DateTimeField(blank=True, null=True)),
                ('retire_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'concept_datatype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptWithRelations',
            fields=[
                ('concept_id', models.AutoField(primary_key=True, serialize=False)),
                ('retired', models.BooleanField(default=False)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_text', models.TextField(blank=True, null=True)),
                ('is_set', models.BooleanField(default=False)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('combination', models.BooleanField(default=False)),
                ('dose_strength', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_daily_dose', models.FloatField(blank=True, null=True)),
                ('minimum_daily_dose', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('retired', models.BooleanField(default=False)),
                ('retired_by', models.IntegerField(blank=True, null=True)),
                ('date_retired', models.DateTimeField(blank=True, null=True)),
                ('retire_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'drug',
                'managed': False,
            },
        ),
    ]
