# Generated by Django 4.2 on 2025-06-26 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0002_initial'),
        ('openmrs_models', '0003_conceptclass_conceptdatatype_conceptwithrelations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisImageMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=255)),
                ('series_instance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('orthanc_study_id', models.CharField(blank=True, max_length=255, null=True)),
                ('orthanc_series_id', models.CharField(blank=True, max_length=255, null=True)),
                ('orthanc_instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('annotations', models.JSONField(blank=True, help_text='영상 주석 및 마킹', null=True)),
                ('roi_coordinates', models.JSONField(blank=True, help_text='관심 영역 좌표', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('soap_diagnosis', models.ForeignKey(db_column='soap_diagnosis_id', on_delete=django.db.models.deletion.CASCADE, related_name='image_mappings', to='soap.soapdiagnosis')),
            ],
            options={
                'verbose_name': '진단-영상 매핑',
                'verbose_name_plural': '진단-영상 매핑 목록',
                'db_table': 'diagnosis_image_mapping',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='diagnosisimagemapping',
            index=models.Index(fields=['soap_diagnosis'], name='idx_mapping_soap'),
        ),
        migrations.AddIndex(
            model_name='diagnosisimagemapping',
            index=models.Index(fields=['study_instance_uid'], name='idx_mapping_study'),
        ),
        migrations.AddIndex(
            model_name='diagnosisimagemapping',
            index=models.Index(fields=['orthanc_study_id'], name='idx_mapping_orthanc'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisimagemapping',
            unique_together={('soap_diagnosis', 'study_instance_uid', 'series_instance_uid')},
        ),
    ]
