# Generated by Django 4.2 on 2025-06-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_models', '0004_diagnosisimagemapping_patientvisithistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisimagemapping',
            options={'managed': True, 'verbose_name': '진단-영상 매핑', 'verbose_name_plural': '진단-영상 매핑 목록'},
        ),
        migrations.AlterModelOptions(
            name='patientvisithistory',
            options={'managed': True, 'ordering': ['-visit_date'], 'verbose_name': '환자 내원 이력', 'verbose_name_plural': '환자 내원 이력 목록'},
        ),
        migrations.AlterModelOptions(
            name='soapdiagnosis',
            options={'managed': True, 'ordering': ['created_date', 'soap_type', 'sequence_number'], 'verbose_name': 'SOAP 진단', 'verbose_name_plural': 'SOAP 진단 목록'},
        ),
        migrations.RenameIndex(
            model_name='soapdiagnosis',
            new_name='idx_soap_patient_encounter',
            old_name='soap_diagno_patient_87eddb_idx',
        ),
        migrations.RenameIndex(
            model_name='soapdiagnosis',
            new_name='idx_soap_icd10',
            old_name='soap_diagno_icd10_c_164c00_idx',
        ),
        migrations.RenameIndex(
            model_name='soapdiagnosis',
            new_name='idx_soap_type_seq',
            old_name='soap_diagno_soap_ty_b39e57_idx',
        ),
        migrations.AlterField(
            model_name='diagnosisimagemapping',
            name='soap_diagnosis',
            field=models.ForeignKey(db_column='soap_diagnosis_id', on_delete=django.db.models.deletion.CASCADE, related_name='image_mappings', to='openmrs_models.soapdiagnosis'),
        ),
        migrations.AddIndex(
            model_name='diagnosisimagemapping',
            index=models.Index(fields=['soap_diagnosis'], name='idx_mapping_soap'),
        ),
        migrations.AddIndex(
            model_name='diagnosisimagemapping',
            index=models.Index(fields=['study_instance_uid'], name='idx_mapping_study'),
        ),
        migrations.AddIndex(
            model_name='diagnosisimagemapping',
            index=models.Index(fields=['orthanc_study_id'], name='idx_mapping_orthanc'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['patient_uuid'], name='idx_visit_patient'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['visit_date'], name='idx_visit_date'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['encounter_uuid'], name='idx_visit_encounter'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['doctor_uuid'], name='idx_visit_doctor'),
        ),
        migrations.AddIndex(
            model_name='soapdiagnosis',
            index=models.Index(fields=['doctor_uuid'], name='idx_soap_doctor'),
        ),
        migrations.AddIndex(
            model_name='soapdiagnosis',
            index=models.Index(fields=['created_date'], name='idx_soap_created'),
        ),
    ]
