# Generated by Django 4.2 on 2025-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_models', '0005_alter_diagnosisimagemapping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientvisithistory',
            table='medical_platform_patient_visit_history',
        ),
    ]
