# Generated by Django 4.2 on 2025-06-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs_models', '0006_alter_patientvisithistory_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientVisitHistory',
        ),
    ]
