# Generated by Django 4.2 on 2025-06-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0002_soapdiagnosis_and_more'),
        ('openmrs_models', '0007_delete_patientvisithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisimagemapping',
            name='soap_diagnosis',
            field=models.ForeignKey(db_column='soap_diagnosis_id', on_delete=django.db.models.deletion.CASCADE, related_name='image_mappings', to='soap.soapdiagnosis'),
        ),
        migrations.DeleteModel(
            name='SoapDiagnosis',
        ),
    ]
