# Generated by Django 5.2.1 on 2025-05-24 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YOLOModelInfo',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('model_version', models.CharField(max_length=100)),
                ('model_path', models.CharField(help_text='모델 파일 경로', max_length=500)),
                ('model_type', models.CharField(choices=[('detection', 'Object Detection'), ('classification', 'Classification')], default='detection', max_length=50)),
                ('target_modality', models.CharField(help_text='대상 Modality (CT, X-ray, MRI)', max_length=50)),
                ('target_body_part', models.CharField(help_text='대상 부위', max_length=100)),
                ('map_50', models.FloatField(blank=True, help_text='mAP@0.5', null=True)),
                ('map_95', models.FloatField(blank=True, help_text='mAP@0.5:0.95', null=True)),
                ('default_confidence_threshold', models.FloatField(default=0.5)),
                ('default_iou_threshold', models.FloatField(default=0.45)),
                ('class_names', models.JSONField(default=list, help_text='클래스 이름 리스트')),
                ('class_colors', models.JSONField(default=dict, help_text='클래스별 색상 매핑')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'yolo_model_info',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('study_uid', models.CharField(db_index=True, max_length=255)),
                ('series_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('total_instances', models.IntegerField(default=0, help_text='분석된 총 인스턴스 수')),
                ('total_detections', models.IntegerField(default=0, help_text='총 detection 수')),
                ('abnormal_instances', models.IntegerField(default=0, help_text='이상 소견이 있는 인스턴스 수')),
                ('max_confidence', models.FloatField(default=0.0, help_text='최고 신뢰도')),
                ('avg_confidence', models.FloatField(default=0.0, help_text='평균 신뢰도')),
                ('detected_labels', models.JSONField(default=dict, help_text="발견된 라벨별 개수 {'pneumonia': 3, 'nodule': 1}")),
                ('analysis_status', models.CharField(choices=[('pending', '대기중'), ('processing', '분석중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('final_diagnosis', models.TextField(blank=True, help_text='의사의 최종 판단', null=True)),
                ('has_critical_findings', models.BooleanField(default=False, help_text='심각한 소견 여부')),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_processing_time', models.FloatField(blank=True, help_text='총 처리 시간(초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_analysis_summary',
                'ordering': ['-analysis_completed_at'],
                'unique_together': {('study_uid', 'series_uid')},
            },
        ),
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('ai_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, help_text='환자 고유 아이디 (P12345)', max_length=100)),
                ('study_uid', models.CharField(db_index=True, help_text='DICOM StudyInstanceUID', max_length=255)),
                ('accession_number', models.CharField(blank=True, db_index=True, help_text='검사 고유번호로 StudyUID 대신 사용 가능', max_length=100, null=True)),
                ('series_uid', models.CharField(db_index=True, help_text='DICOM Series Instance UID', max_length=255)),
                ('instance_uid', models.CharField(db_index=True, help_text='DICOM SOP Instance UID', max_length=255)),
                ('label', models.CharField(help_text='라벨 (예: Pneumothorax, Nodule)', max_length=200)),
                ('bbox', models.JSONField(help_text='바운딩박스 좌표 [x1, y1, x2, y2]')),
                ('confidence_score', models.FloatField(help_text='신뢰도 (0.0 ~ 1.0)')),
                ('ai_text', models.TextField(blank=True, help_text='요약 소견, radiomics 정량적 수치 등', null=True)),
                ('model_version', models.CharField(default='yolov8', help_text='사용된 AI 모델 버전', max_length=100)),
                ('analysis_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='분석 수행 시간')),
                ('processing_time', models.FloatField(blank=True, help_text='처리 시간(초)', null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', '검토대기'), ('confirmed', '확인됨'), ('rejected', '거부됨'), ('modified', '수정됨')], default='pending', help_text='의사 검토 상태', max_length=20)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, help_text='검토한 의사', max_length=200, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_results',
                'ordering': ['-analysis_datetime', '-confidence_score'],
                'indexes': [models.Index(fields=['patient_id', 'study_uid'], name='ai_results_patient_091f3e_idx'), models.Index(fields=['study_uid', 'series_uid'], name='ai_results_study_u_52e840_idx'), models.Index(fields=['label', 'confidence_score'], name='ai_results_label_18112a_idx'), models.Index(fields=['analysis_datetime'], name='ai_results_analysi_8f7e16_idx')],
            },
        ),
    ]
