# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='UNKNOWN', max_length=100)),
                ('patient_id', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=50)),
                ('test_type', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField()),
            ],
        ),
    ]
