# Generated by Django 5.2 on 2025-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('doctor_id', models.UUIDField()),
                ('panel', models.CharField(max_length=100)),
                ('tests', models.JSONField()),
                ('order_date', models.DateField()),
                ('status', models.CharField(default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
