# Generated by Django 4.2 on 2025-06-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_emr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doctor_id',
            field=models.CharField(max_length=100),
        ),
    ]
