# Generated by Django 5.2.1 on 2025-05-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('orthanc_patient_id', models.CharField(max_length=255, verbose_name='Orthanc 환자 PublicId')),
                ('openmrs_patient_uuid', models.CharField(max_length=38, verbose_name='OpenMRS 환자 UUID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('PENDING', '대기중'), ('SYNCED', '동기화됨'), ('ERROR', '오류')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_mapping',
                'indexes': [models.Index(fields=['orthanc_patient_id'], name='patient_map_orthanc_e55d9f_idx'), models.Index(fields=['openmrs_patient_uuid'], name='patient_map_openmrs_1442d0_idx'), models.Index(fields=['created_date'], name='patient_map_created_032a0f_idx'), models.Index(fields=['last_sync'], name='patient_map_last_sy_77e10e_idx'), models.Index(fields=['sync_status'], name='patient_map_sync_st_ea283a_idx')],
                'unique_together': {('orthanc_patient_id', 'openmrs_patient_uuid')},
            },
        ),
    ]
