# Generated by Django 4.2 on 2025-05-26 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_estimated', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.IntegerField(blank=True, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('person_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('family_name', models.CharField(max_length=50)),
                ('family_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('family_name_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(blank=True, null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'person_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('internalId', models.AutoField(primary_key=True, serialize=False)),
                ('resourceType', models.IntegerField()),
                ('publicId', models.CharField(max_length=255)),
                ('parentId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('SYNCED', '동기화됨'), ('PENDING', '대기중'), ('ERROR', '오류')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('openmrs_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orthanc_mappings', to='medical_integration.patient')),
                ('orthanc_patient', models.ForeignKey(limit_choices_to={'resourceType': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='patient_mappings', to='medical_integration.resources')),
            ],
            options={
                'db_table': 'patient_mapping',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['created_date'], name='patient_map_created_032a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['last_sync'], name='patient_map_last_sy_77e10e_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['sync_status'], name='patient_map_sync_st_ea283a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientmapping',
            unique_together={('orthanc_patient', 'openmrs_patient')},
        ),
    ]
