# Generated by Django 4.2 on 2025-05-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('changed_by', models.IntegerField(null=True)),
                ('date_changed', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(null=True)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('birthdate_estimated', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
                ('death_date', models.DateField(null=True)),
                ('cause_of_death', models.IntegerField(null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('changed_by', models.IntegerField(null=True)),
                ('date_changed', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(null=True)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=255, null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('person_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('prefix', models.CharField(max_length=50, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('family_name', models.CharField(max_length=50)),
                ('family_name2', models.CharField(max_length=50, null=True)),
                ('family_name_suffix', models.CharField(max_length=50, null=True)),
                ('creator', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('voided', models.BooleanField(default=False)),
                ('voided_by', models.IntegerField(null=True)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=255, null=True)),
                ('changed_by', models.IntegerField(null=True)),
                ('date_changed', models.DateTimeField(null=True)),
                ('uuid', models.CharField(max_length=38, unique=True)),
            ],
            options={
                'db_table': 'person_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('internalId', models.AutoField(primary_key=True, serialize=False)),
                ('resourceType', models.IntegerField()),
                ('publicId', models.CharField(max_length=255)),
                ('parentId', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('SYNCED', '동기화됨'), ('PENDING', '대기중'), ('ERROR', '오류')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(null=True)),
                ('orthanc_patient_id', models.IntegerField()),
                ('openmrs_patient_id', models.IntegerField()),
            ],
            options={
                'db_table': 'patient_mapping',
                'managed': True,
                'indexes': [
                    models.Index(fields=['created_date'], name='patient_map_created_032a0f_idx'),
                    models.Index(fields=['last_sync'], name='patient_map_last_sy_77e10e_idx'),
                    models.Index(fields=['sync_status'], name='patient_map_sync_st_ea283a_idx'),
                ],
                'unique_together': {('orthanc_patient_id', 'openmrs_patient_id')},
            },
        ),
    ]
