# Generated by Django 4.2 on 2025-06-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmapping',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_orthanc_e55d9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_patient_745b11_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_created_032a0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_last_sy_77e10e_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_sync_st_ea283a_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_mapping_5b04ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientmapping',
            name='patient_map_confide_8c5d66_idx',
        ),
        migrations.AlterUniqueTogether(
            name='patientmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='진료 완료 날짜/시간', null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='total_wait_minutes',
            field=models.IntegerField(blank=True, help_text='총 대기 시간(분)', null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='treatment_start_time',
            field=models.DateTimeField(blank=True, help_text='진료 시작 시간', null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='wait_start_time',
            field=models.DateTimeField(blank=True, help_text='대기 시작 시간', null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='assigned_room',
            field=models.IntegerField(blank=True, help_text='배정된 진료실 번호', null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='display',
            field=models.CharField(blank=True, help_text='환자 표시명', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['patient_identifier', 'is_active'], name='patient_map_patient_d45727_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['created_date', 'mapping_type'], name='patient_map_created_f3128a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['status', 'is_active'], name='patient_map_status_ae8eda_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['assigned_room', 'is_active'], name='patient_map_assigne_23c562_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['completion_date'], name='patient_map_complet_a96127_idx'),
        ),
        migrations.RemoveField(
            model_name='patientmapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientmapping',
            name='notes',
        ),
    ]
