# Generated by Django 5.2 on 2025-06-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('uuid', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='patient_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='DICOM Patient ID 또는 OpenMRS Patient Identifier', max_length=255, null=True, verbose_name='Patient Identifier (DICOM Patient ID)'),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='mapping_type',
            field=models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동'), ('BATCH', '일괄'), ('IDENTIFIER_BASED', 'Patient ID 기반')], default='MANUAL', max_length=20, verbose_name='매핑 타입'),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('SYNCED', '동기화됨'), ('ERROR', '오류'), ('AUTO_MAPPED', '자동매핑됨'), ('MANUAL_MAPPED', '수동매핑됨'), ('IDENTIFIER_MATCHED', 'Patient ID 매칭됨')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['patient_identifier'], name='patient_map_patient_745b11_idx'),
        ),
        migrations.AddField(
            model_name='provider',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='medical_integration.person'),
        ),
    ]
