# Generated by Django 5.2.1 on 2025-06-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmapping',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='자동 매핑 신뢰도 (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='created_by',
            field=models.CharField(blank=True, help_text='매핑을 생성한 사용자 또는 시스템', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='mapping_criteria',
            field=models.JSONField(blank=True, help_text='매핑에 사용된 기준 정보 (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='mapping_type',
            field=models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동'), ('BATCH', '일괄')], default='MANUAL', max_length=10, verbose_name='매핑 타입'),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='notes',
            field=models.TextField(blank=True, help_text='매핑에 대한 추가 메모', null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='openmrs_patient_uuid',
            field=models.CharField(db_index=True, max_length=38, verbose_name='OpenMRS 환자 UUID'),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='orthanc_patient_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Orthanc 환자 PublicId'),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('SYNCED', '동기화됨'), ('ERROR', '오류'), ('AUTO_MAPPED', '자동매핑됨'), ('MANUAL_MAPPED', '수동매핑됨')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['mapping_type'], name='patient_map_mapping_5b04ee_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmapping',
            index=models.Index(fields=['confidence_score'], name='patient_map_confide_8c5d66_idx'),
        ),
    ]
