# Generated by Django 4.2 on 2025-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0002_alter_patientmapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmapping',
            name='assigned_room',
            field=models.IntegerField(blank=True, default=None, help_text='배정된 진료실 번호', null=True),
        ),
    ]
