# Generated by Django 4.2 on 2025-06-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0002_person_provider_patientmapping_patient_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmapping',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='mapping_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='mapping_type',
            field=models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동'), ('BATCH', '일괄'), ('IDENTIFIER_BASED', 'Patient ID 기반')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='openmrs_patient_uuid',
            field=models.CharField(db_index=True, max_length=38),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='orthanc_patient_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientmapping',
            name='patient_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
