# Generated by Django 5.2 on 2025-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0003_alter_patientmapping_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SPO2', 'SpO₂ 경고'), ('DELAY', '검사 지연'), ('AI_ERR', 'AI 판독 오류')], help_text='알림 종류 코드', max_length=10)),
                ('message', models.TextField(help_text='알림 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='알림 생성 시각')),
                ('is_read', models.BooleanField(default=False, help_text='읽음 여부')),
            ],
            options={
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
