# Generated by Django 4.2 on 2025-06-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0003_alter_patientmapping_assigned_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDSSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=16)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_mapping', models.ForeignKey(help_text='예측 대상이 된 환자 매핑 정보', on_delete=django.db.models.deletion.CASCADE, related_name='cdss_results', to='medical_integration.patientmapping')),
            ],
            options={
                'db_table': 'cdss_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
