# Generated by Django 4.2 on 2025-07-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0004_cdssresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdssresult',
            name='shap_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
