# Generated by Django 4.2 on 2025-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0004_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmapping',
            name='assigned_room',
            field=models.IntegerField(blank=True, help_text='진료실 번호', null=True),
        ),
    ]
