# Generated by Django 4.2 on 2025-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_integration', '0005_patientmapping_assigned_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmapping',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientmapping',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='알림 생성 시간'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False, help_text='읽음 유무'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('SPO2', 'SpO₂ 경고'), ('DELAY', '검사 지역'), ('AI_ERR', 'AI 판단 오류')], help_text='알림 종류 코드', max_length=10),
        ),
    ]
