# Generated by Django 5.2.3 on 2025-06-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedulecommon_updated_at_scheduleris_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalschedule',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료 일시'),
        ),
        migrations.AddField(
            model_name='schedulecommon',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료 일시'),
        ),
        migrations.AddField(
            model_name='scheduleris',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료 일시'),
        ),
    ]
