# Generated by Django 5.2.1 on 2025-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_personalschedule_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True, verbose_name='검사실 ID')),
                ('name', models.CharField(max_length=50, verbose_name='검사실명')),
                ('room_type', models.CharField(choices=[('CR', 'CR (X-ray)'), ('CT', 'CT (Computed Tomography)'), ('MR', 'MR (MRI)'), ('US', 'US (Ultrasound)'), ('NM', 'NM (Nuclear Medicine)'), ('PT', 'PT (PET Scan)'), ('DX', 'DX (Digital Radiography)'), ('XA', 'XA (Angiography)'), ('MG', 'MG (Mammography)')], max_length=20, verbose_name='검사실 유형')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '검사실',
                'verbose_name_plural': '검사실들',
                'db_table': 'exam_rooms',
                'ordering': ['room_id'],
            },
        ),
    ]
