# Generated by Django 5.2 on 2025-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDSSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.IntegerField()),
                ('test_type', models.CharField(max_length=100)),
                ('component_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('verified_by', models.IntegerField()),
                ('verified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'lis_cdss_cdssrecord',
            },
        ),
    ]
