# Generated by Django 4.2 on 2025-06-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lis_cdss', '0002_cdssresult_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverFunctionSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALT', models.FloatField()),
                ('AST', models.FloatField()),
                ('ALP', models.FloatField()),
                ('Albumin', models.FloatField()),
                ('Total_Bilirubin', models.FloatField()),
                ('Direct_Bilirubin', models.FloatField()),
                ('prediction', models.BooleanField(blank=True, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
