# Generated by Django 4.2 on 2025-06-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        ('lis_cdss', '0003_liverfunctionsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverfunctionsample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.sample'),
        ),
    ]
