# Generated by Django 4.2 on 2025-06-26 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticecommon',
            options={'ordering': ['-is_pinned', 'notice_type', '-created_at'], 'verbose_name': '시스템 공지사항', 'verbose_name_plural': '시스템 공지사항들'},
        ),
        migrations.AlterModelOptions(
            name='noticeris',
            options={'ordering': ['-is_pinned', 'notice_type', '-created_at'], 'verbose_name': '영상의학과 공지사항', 'verbose_name_plural': '영상의학과 공지사항들'},
        ),
        migrations.RemoveField(
            model_name='noticecommon',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='noticeris',
            name='is_important',
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='created_by',
            field=models.CharField(default='admin', max_length=100, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='notice_type',
            field=models.CharField(choices=[('important', '중요'), ('update', '업데이트'), ('maintenance', '점검'), ('general', '일반')], default='general', max_length=20, verbose_name='공지 유형'),
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일'),
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='created_by',
            field=models.CharField(default='admin', max_length=100, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='notice_type',
            field=models.CharField(choices=[('important', '중요'), ('update', '업데이트'), ('maintenance', '점검'), ('general', '일반')], default='general', max_length=20, verbose_name='공지 유형'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='target_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대상 부서'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='noticecommon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='noticecommon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='noticeris',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='noticeris',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
