# Generated by Django 5.2.3 on 2025-06-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worklists', '0003_alter_studyrequest_assigned_radiologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='예: consent, report, export, consultation, certificate', max_length=20, unique=True, verbose_name='서류 코드')),
                ('name', models.CharField(help_text='예: 조영제 동의서, 판독 결과지', max_length=50, verbose_name='서류명')),
                ('requires_signature', models.BooleanField(default=False, help_text='True: 서명+스캔 필요, False: 바로 발급', verbose_name='서명 필요')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '서류 종류',
                'verbose_name_plural': '서류 종류',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_content', models.TextField(help_text='HTML 템플릿 또는 마크다운', verbose_name='템플릿 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='pacsdocs.documenttype', verbose_name='서류 종류')),
            ],
            options={
                'verbose_name': '서류 템플릿',
                'verbose_name_plural': '서류 템플릿',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('selected', '선택됨'), ('generated', '생성됨'), ('signature_waiting', '서명대기'), ('scan_waiting', '스캔대기'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='생성 일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('generated_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='생성된 파일 경로')),
                ('scanned_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='스캔된 파일 경로')),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='처리자')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='worklists.studyrequest', verbose_name='검사 요청')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='pacsdocs.documenttype', verbose_name='서류 종류')),
            ],
            options={
                'verbose_name': '서류 요청',
                'verbose_name_plural': '서류 요청',
                'ordering': ['-created_at'],
                'unique_together': {('study_request', 'document_type')},
            },
        ),
    ]
