# Generated by Django 5.2.3 on 2025-06-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기 (바이트)'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='원본 파일명'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='업로드 일시'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='환자가 서명한 동의서 스캔 파일', null=True, upload_to='documents/uploads/%Y/%m/%d/', verbose_name='업로드된 파일'),
        ),
    ]
