# Generated by Django 5.2.1 on 2025-06-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_role'),
        ('schedules', '0004_examroom'),
        ('worklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrequest',
            options={'ordering': ['-request_datetime'], 'verbose_name': '검사 요청', 'verbose_name_plural': '검사 요청들'},
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='실제 종료 시간'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='실제 시작 시간'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='assigned_radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor', verbose_name='배정 방사선사'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.examroom', verbose_name='배정 검사실'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='estimated_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='예상 소요시간(분)'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='특이사항'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='priority',
            field=models.CharField(choices=[('일반', '일반'), ('응급', '응급'), ('긴급', '긴급')], default='일반', max_length=10, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='예약 종료 시간'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='접수 번호'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='birth_date',
            field=models.DateField(verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='body_part',
            field=models.CharField(max_length=50, verbose_name='검사 부위'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='interpreting_physician',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='판독의'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='modality',
            field=models.CharField(choices=[('CR', 'CR (X-ray)'), ('CT', 'CT (Computed Tomography)'), ('MR', 'MR (MRI)'), ('US', 'US (Ultrasound)'), ('NM', 'NM (Nuclear Medicine)'), ('PT', 'PT (PET Scan)'), ('DX', 'DX (Digital Radiography)'), ('XA', 'XA (Angiography)'), ('MG', 'MG (Mammography)')], max_length=20, verbose_name='검사 장비'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='patient_id',
            field=models.CharField(max_length=20, verbose_name='환자 ID'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='patient_name',
            field=models.CharField(max_length=100, verbose_name='환자명'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='report_status',
            field=models.CharField(choices=[('대기', '대기'), ('작성중', '작성중'), ('작성완료', '작성완료')], default='대기', max_length=20, verbose_name='리포트 상태'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='요청 일시'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='requesting_physician',
            field=models.CharField(max_length=100, verbose_name='의뢰의'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='scheduled_exam_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='예약 검사 시간'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='sex',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='study_status',
            field=models.CharField(choices=[('대기', '대기'), ('검사대기', '검사대기'), ('검사중', '검사중'), ('검사완료', '검사완료'), ('취소', '취소')], default='대기', max_length=20, verbose_name='검사 상태'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='study_uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='검사 UID'),
        ),
    ]
