# Generated by Django 5.2.3 on 2025-06-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_role'),
        ('worklists', '0002_alter_studyrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='assigned_radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor', verbose_name='배정 판독의(영상전문의)'),
        ),
    ]
