# Generated by Django 4.2 on 2025-06-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('doctor_id', models.UUIDField(blank=True, null=True)),
                ('raw_data', models.JSONField(help_text='요청 payload 전체')),
                ('system', models.CharField(default='OCS-Integration', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
