# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LISLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('order', '오더 생성'), ('sample', '샘플 등록'), ('result', '결과 등록')], max_length=10)),
                ('patient_id', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_detail', models.TextField(blank=True)),
                ('result_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
