# Generated by Django 5.2.3 on 2025-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정명')),
                ('datetime', models.DateTimeField(verbose_name='일시')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '전체 일정',
                'verbose_name_plural': '전체 일정들',
                'db_table': 'schedule_common',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정명')),
                ('datetime', models.DateTimeField(verbose_name='일시')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '부서 일정',
                'verbose_name_plural': '부서 일정들',
                'db_table': 'schedule_ris',
                'ordering': ['datetime'],
            },
        ),
    ]
