# Generated by Django 5.2.1 on 2025-06-23 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_examroom'),
        ('worklists', '0002_alter_studyrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalschedule',
            name='exam_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.examroom', verbose_name='검사실'),
        ),
        migrations.AddField(
            model_name='personalschedule',
            name='schedule_type',
            field=models.CharField(choices=[('일반', '일반 일정'), ('검사', '검사 일정')], default='일반', max_length=10, verbose_name='일정 유형'),
        ),
        migrations.AddField(
            model_name='personalschedule',
            name='study_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklists.studyrequest', verbose_name='연결된 검사 요청'),
        ),
        migrations.AlterField(
            model_name='personalschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
