# Generated by Django 5.2.3 on 2025-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('department', models.CharField(default='영상의학과', max_length=100, verbose_name='진료과')),
                ('medical_id', models.CharField(max_length=50, unique=True, verbose_name='의료진식별번호')),
                ('role', models.CharField(default='방사선사', max_length=50, verbose_name='역할')),
                ('status', models.CharField(choices=[('온라인', '온라인'), ('자리비움', '자리비움')], default='온라인', max_length=20, verbose_name='상태')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '의사',
                'verbose_name_plural': '의사들',
                'db_table': 'doctors',
            },
        ),
    ]
