# Generated by Django 5.2.3 on 2025-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='의사', max_length=50, verbose_name='역할'),
        ),
    ]
