# Generated by Django 5.2.3 on 2025-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeris',
            options={'ordering': ['-created_at'], 'verbose_name': '방사선과 공지사항', 'verbose_name_plural': '방사선과 공지사항들'},
        ),
        migrations.AddField(
            model_name='noticecommon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='noticeris',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
