# Generated by Django 5.2.3 on 2025-06-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_noticeris_options_noticecommon_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeris',
            options={'ordering': ['-created_at'], 'verbose_name': ' 영상의학과 공지사항', 'verbose_name_plural': '영상의학과 공지사항들'},
        ),
    ]
