# Generated by Django 5.2.3 on 2025-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='환자 ID', max_length=100)),
                ('study_uid', models.CharField(db_index=True, help_text='StudyInstanceUID', max_length=255)),
                ('series_uid', models.CharField(blank=True, help_text='SeriesInstanceUID', max_length=255, null=True)),
                ('instance_uid', models.CharField(blank=True, help_text='InstanceUID', max_length=255, null=True)),
                ('instance_number', models.IntegerField(blank=True, help_text='Instance Number', null=True)),
                ('doctor_id', models.CharField(help_text='판독의 ID', max_length=50)),
                ('doctor_name', models.CharField(help_text='판독의 이름', max_length=100)),
                ('label', models.CharField(help_text='주석 라벨', max_length=100)),
                ('shape_type', models.CharField(choices=[('rectangle', '사각형'), ('circle', '원형'), ('line', '길이측정')], help_text='도형 종류', max_length=20)),
                ('coordinates', models.JSONField(help_text='도형 좌표 정보')),
                ('dr_text', models.TextField(blank=True, help_text='의사 의견/메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dr_annotations_annotationresult',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['study_uid'], name='dr_annotati_study_u_181a8d_idx'), models.Index(fields=['patient_id'], name='dr_annotati_patient_d5f1fa_idx'), models.Index(fields=['doctor_name'], name='dr_annotati_doctor__bb6d70_idx'), models.Index(fields=['shape_type'], name='dr_annotati_shape_t_49a533_idx'), models.Index(fields=['created_at'], name='dr_annotati_created_7928a8_idx')],
            },
        ),
    ]
