# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='환자 ID (PACS에서 가져옴)', max_length=100)),
                ('study_uid', models.CharField(db_index=True, help_text='StudyInstanceUID', max_length=255)),
                ('series_uid', models.CharField(blank=True, help_text='SeriesInstanceUID', max_length=255, null=True)),
                ('instance_uid', models.CharField(blank=True, help_text='InstanceUID (슬라이스 고유 ID)', max_length=255, null=True)),
                ('instance_number', models.IntegerField(blank=True, help_text='인스턴스 넘버(이미지 인덱스)', null=True)),
                ('doctor_id', models.CharField(default='DR001', help_text='판독의 ID', max_length=50)),
                ('doctor_name', models.CharField(default='김영상', help_text='판독의 이름', max_length=100)),
                ('label', models.CharField(help_text='의사가 마킹한 라벨', max_length=100)),
                ('bbox', models.JSONField(help_text='바운딩박스 좌표 [x1, y1, x2, y2]')),
                ('dr_text', models.TextField(blank=True, help_text='선택적 코멘트 (의견, 진단 등)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dr_annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='annotationresult',
            index=models.Index(fields=['study_uid'], name='dr_annotati_study_u_cd88e0_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationresult',
            index=models.Index(fields=['series_uid'], name='dr_annotati_series__2b0054_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationresult',
            index=models.Index(fields=['instance_uid'], name='dr_annotati_instanc_0178a0_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationresult',
            index=models.Index(fields=['patient_id'], name='dr_annotati_patient_c2dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationresult',
            index=models.Index(fields=['doctor_id'], name='dr_annotati_doctor__404e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationresult',
            index=models.Index(fields=['created_at'], name='dr_annotati_created_151b2f_idx'),
        ),
    ]
