# Generated by Django 5.2.3 on 2025-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='환자 ID (PACS에서 가져옴)', max_length=100)),
                ('study_uid', models.CharField(db_index=True, help_text='StudyInstanceUID', max_length=255, unique=True)),
                ('doctor_id', models.CharField(default='DR001', help_text='판독의 ID', max_length=50)),
                ('doctor_name', models.CharField(default='김영상', help_text='판독의 이름', max_length=100)),
                ('dr_report', models.TextField(blank=True, help_text='판독 소견')),
                ('report_status', models.CharField(choices=[('draft', '초안'), ('completed', '완료'), ('approved', '승인')], default='draft', help_text='판독 상태', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dr_reports',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['study_uid'], name='dr_reports_study_u_39e19d_idx'), models.Index(fields=['patient_id'], name='dr_reports_patient_d2e178_idx'), models.Index(fields=['doctor_id'], name='dr_reports_doctor__e1d85e_idx'), models.Index(fields=['report_status'], name='dr_reports_report__5158e1_idx'), models.Index(fields=['created_at'], name='dr_reports_created_281d2f_idx')],
            },
        ),
    ]
