# Generated by Django 5.2.3 on 2025-06-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drreport',
            name='doctor_id',
            field=models.CharField(help_text='판독의 ID (워크리스트에서 가져옴)', max_length=50),
        ),
        migrations.AlterField(
            model_name='drreport',
            name='doctor_name',
            field=models.CharField(help_text='판독의 이름 (워크리스트에서 가져옴)', max_length=100),
        ),
        migrations.AlterField(
            model_name='drreport',
            name='patient_id',
            field=models.CharField(help_text='환자 ID (AI 분석 결과에서 가져옴)', max_length=100),
        ),
    ]
