# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomIdentifiers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagGroup', models.IntegerField()),
                ('tagElement', models.IntegerField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'DicomIdentifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainDicomTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagGroup', models.IntegerField()),
                ('tagElement', models.IntegerField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'MainDicomTags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'Metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ResourceMetadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('internalId', models.AutoField(primary_key=True, serialize=False)),
                ('resourceType', models.IntegerField()),
                ('publicId', models.CharField(max_length=255)),
                ('parentId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ResourceTags',
                'managed': False,
            },
        ),
    ]
