# Generated by Django 4.2 on 2025-06-26 15:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisitHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_uuid', models.CharField(db_index=True, max_length=38)),
                ('visit_uuid', models.CharField(blank=True, help_text='OpenMRS Visit UUID', max_length=38, null=True)),
                ('encounter_uuid', models.CharField(blank=True, help_text='OpenMRS Encounter UUID', max_length=38, null=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(default='OUTPATIENT', max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', '예약됨'), ('ARRIVED', '도착'), ('IN_PROGRESS', '진료중'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('NO_SHOW', '미출석')], default='SCHEDULED', max_length=20)),
                ('chief_complaint', models.TextField(blank=True, help_text='주요 증상', null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_uuid', models.CharField(blank=True, max_length=38, null=True)),
                ('primary_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_diagnoses', models.JSONField(blank=True, null=True)),
                ('prescriptions', models.JSONField(blank=True, null=True)),
                ('procedures', models.JSONField(blank=True, null=True)),
                ('imaging_studies', models.JSONField(blank=True, help_text='연관된 영상 검사 목록', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '환자 내원 이력',
                'verbose_name_plural': '환자 내원 이력 목록',
                'db_table': 'medical_platform_patient_visit_history',
                'ordering': ['-visit_date'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['patient_uuid'], name='idx_visit_patient'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['visit_date'], name='idx_visit_date'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['encounter_uuid'], name='idx_visit_encounter'),
        ),
        migrations.AddIndex(
            model_name='patientvisithistory',
            index=models.Index(fields=['doctor_uuid'], name='idx_visit_doctor'),
        ),
    ]
