# Generated by Django 4.2 on 2025-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('study_uid', models.CharField(max_length=255)),
                ('series_uid', models.CharField(max_length=255)),
                ('instance_uid', models.CharField(max_length=255)),
                ('instance_number', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('bbox', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('ai_text', models.TextField(blank=True)),
                ('modality', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_analysis_results',
            },
        ),
    ]
